# Generated by Django 3.1 on 2020-08-29 16:23

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forceaccountpackage',
            name='docfile',
            field=models.FileField(storage=custom_storages.GeneratedStorage(), upload_to=''),
        ),
    ]
