# Generated by Django 3.1 on 2020-08-30 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200829_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='forceaccountpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 30, 8, 11, 40, 31160)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 30, 8, 11, 51, 271171)),
            preserve_default=False,
        ),
    ]
